# frontend/social-web-spa/Dockerfile

FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN npm run build

FROM node:22-alpine AS run
WORKDIR /app

RUN npm i -g serve
COPY --from=build /app/dist ./dist

ENV PORT=8000
EXPOSE 8000

CMD ["sh", "-c", "serve -s dist -l $PORT"]